### PR TITLE
Add filters for activity, aum, ant, and score

### PR DESCRIPTION
**Pull request by sembrestels**

### CODE REVIEW

**Comment by onbjerg** [comment]
Are you going to add something else to this PR?

**Comment by lkngtn** [comment]
What's the status of this one @sembrestels ?

**Comment by sembrestels** [comment]
Not that important to push this forward since @onbjerg fixed the schema problem in https://github.com/1Hive/apiary/commit/bbf4e0acc35ae375a87c589a1b2e32618ad7985a. You can close this PR and we add ANT again when fixing #144.

**Comment by lkngtn** [comment]
Thanks for the clarification @sembrestels 👍

**Pull request closed without merging**
