### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by sakthivel9963**

### CODE REVIEW

**Comment by onbjerg** [comment]
Hi @sakthivel9963,

Thank you for contributing to Apiary!

As far as I know, we haven't really settled on a code of conduct for 1Hive projects yet. I'll bring this up at our next meeting, but for now this means that this PR will be blocked for a while.

However, one thing I would request is that you move the code of conduct file in to the `.github` folder as I am trying to keep the root somewhat clean of files 😊If you could squash your commits that would also be very nice!

**Comment by sakthivel9963** [comment]
I will make the required change and open pull request.

**Comment by sakthivel9963** [comment]
I have change the file according to the requirement.

**Comment by onbjerg** [comment]
Great! I'll check with the rest of the Hive to see what kind of CoC we want 😊

**Pull request merged**
